### PR TITLE
ODIN-49: Added support for Multi-Tenant login utility files if presen…

### PR DESCRIPTION
**Pull request by pgwatinfor**
…t when Odin serve command is launched

### CODE REVIEW

**Comment by anhallbe** [comment]
The code currently adds a separate config file for the webpack-dev-server (in addition to what is already in `odin.json`). Most of the contents of the file (e.g HTTP interception) should not really be touched by the user.

I'd prefer if we could handle this inside the scope of the CLI instead, rather than as a file in the workspace. Same goes for the `authorizationheader.json` and `cookieheader.json`. These files should not really be read or modified by the user, and they may contain sensitive data, so they should not be a part of the project source code.

I think the tooling should be improved by:

1. Keep all the configuration that the user should see and modify in `odin.json`
2. Keep logic for the proxy (http middleware) in the CLI tool memory, or in a hidden/temp directory (similar to how proxy-conf.json is stored in $TEMP).

I'll take a look and see if I can come up with some suggestions.

**Comment by pgwatinfor** [comment]
Great suggestion to put the header files in the temp directory to make it cleaner, but for sensitivity I don't agree as the developer already have the ION token in the source code and easily can examine the cookies.
I'm really interested to know if you manage to hook up the events in the odin.json file, a thing I didn't resolve.

**Comment by anhallbe** [comment]
@pgwatinfor I tried to replicate your code, with the following changes:

1. Proxy middleware logic is in TypeScript (https://github.com/infor-cloud/m3-h5-sdk/blob/mt-proxy/cli/src/mtauth.ts), for a little bit of type-safety.
2. Added "--multi-tenant" option to "serve" command
3. Requires no changes to odin.json or a separate proxy config file.

Changes here: https://github.com/infor-cloud/m3-h5-sdk/tree/mt-proxy

Let me know what you think. Do you see any issues?

**Comment by pgwatinfor** [comment]
Much better, looks great!

**Comment by anhallbe** [comment]
@pgwatinfor I'm closing this PR. Your contribution (modified by me in 8c49ae619f9f287ef6a26ce0f91b71a9db0b7a52) was added in v2.1.0.

Thanks a lot! Feel free to continue contributing with feedback, issues, pull-requests, and of course the work on the MT Login util.

**Pull request closed without merging**
